name: build-node-ci
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v4

      - name : Setup Node.js desde action
        uses: pparram/loteria-devops-resources/.github/actions/build/build-node-express@main
        with:
          node-version: ${{ matrix.node-version }}
      
      # - name: Setup Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: ${{ matrix.node-version }}
      #     cache: 'npm'

      # - name: Run de instalacion
      #   run: |
      #     npm install
      #     npm run build

      - name: Upload build artefact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.run_id }}
          path: dist/
          retention-days: 14
  deploy:
    name: Dummy Deploy
    needs: build
    runs-on: ubuntu-tatest
    environment:
      name: node-backend-dev
      url: https://www.google.com

    steps:
      - name: Descarga artefacto
        uses: actions/dowload-artifact@v4
        with:
          name: ${{ github.run_id }}

      - name: Imprimir variables de entorno
        run: |
          echo "Secret VAR: ${{ secrets.SECRET_KEY }}"
          echo "Environment VAR: ${{ vars.SITE_URL }}"


      
