name: Usar un template

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Usar template o action reutilizable
        uses: pparram/loteria-devops-resources/.github/actions/helpers/hello-world@main
        with:
          comentario: 'Se imprimio el comentario'
